import { Account } from "./account-types";

export const MOCK_ACCOUNTS: Account[] = [
  {
    id: "acc-1",
    name: "Total Wine & More",
    chain: "Total Wine",
    type: "off-premise",
    status: "active",
    address: "123 Beverage Blvd",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    contactName: "James Wilson",
    contactPhone: "(212) 555-0100",
    contactEmail: "jwilson@totalwine.example.com",
    distributorAccountIds: {
      "Southern Glazers": "SG-99412",
      "Empire Merchants": "EM-0012",
    },
    profile: {
      venueSubType: "big-box-retail",
      displayCount: 4,
      coldBoxCount: 12,
      hasWindows: true,
      shelfFacings: 24,
      backbarPresence: false,
      menuPlacement: false,
      footTrafficEstimate: "high",
      notes: "Massive foot traffic on weekends. High visibility endcaps.",
      lastSurveyDate: "2026-03-01",
    },
    eventsHosted: 14,
    lastEventDate: "2026-03-10",
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "acc-2",
    name: "The Dead Rabbit",
    type: "on-premise",
    status: "active",
    address: "30 Water St",
    city: "New York",
    state: "NY",
    zipCode: "10004",
    contactName: "Sarah Jenkins",
    contactPhone: "(212) 555-0199",
    distributorAccountIds: {
      "Empire Merchants": "EM-5512",
    },
    profile: {
      venueSubType: "cocktail-bar",
      displayCount: 0,
      coldBoxCount: 3,
      hasWindows: true,
      shelfFacings: 0,
      backbarPresence: true,
      menuPlacement: true,
      footTrafficEstimate: "high",
      notes: "Premier cocktail account. Menu placement is highly competitive.",
      lastSurveyDate: "2026-02-15",
    },
    eventsHosted: 5,
    lastEventDate: "2026-02-28",
    createdAt: "2024-03-22T08:00:00Z",
    updatedAt: "2026-02-15T10:00:00Z",
  },
  {
    id: "acc-3",
    name: "Whole Foods Market",
    chain: "Whole Foods",
    type: "off-premise",
    status: "active",
    address: "214 3rd Ave",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11215",
    contactName: "David Chen",
    contactPhone: "(718) 555-0188",
    distributorAccountIds: {
      "Southern Glazers": "SG-11002",
    },
    profile: {
      venueSubType: "grocery",
      displayCount: 2,
      coldBoxCount: 8,
      hasWindows: true,
      shelfFacings: 12,
      backbarPresence: false,
      menuPlacement: false,
      footTrafficEstimate: "high",
      notes: "Strict organic/natural requirements for endcap displays.",
      lastSurveyDate: "2026-01-20",
    },
    eventsHosted: 8,
    lastEventDate: "2026-02-10",
    createdAt: "2024-06-10T08:00:00Z",
    updatedAt: "2026-01-20T10:00:00Z",
  },
  {
    id: "acc-4",
    name: "Bob's Corner Liquors",
    type: "off-premise",
    status: "prospect",
    address: "412 Main St",
    city: "Hoboken",
    state: "NJ",
    zipCode: "07030",
    contactName: "Robert Smith",
    contactPhone: "(201) 555-0122",
    distributorAccountIds: {
      "Allied Beverage": "AB-8821",
    },
    profile: {
      venueSubType: "liquor-store",
      displayCount: 1,
      coldBoxCount: 4,
      hasWindows: false,
      shelfFacings: 4,
      backbarPresence: false,
      menuPlacement: false,
      footTrafficEstimate: "medium",
      notes: "Good local neighborhood spot. Owner open to tastings.",
    },
    eventsHosted: 0,
    createdAt: "2026-02-01T08:00:00Z",
    updatedAt: "2026-02-01T08:00:00Z",
  },
  {
    id: "acc-5",
    name: "Moxy Times Square (Magic Hour)",
    chain: "Moxy Hotels",
    type: "on-premise",
    status: "active",
    address: "485 7th Ave",
    city: "New York",
    state: "NY",
    zipCode: "10018",
    contactName: "Elena Rodriguez",
    contactPhone: "(212) 555-0144",
    profile: {
      venueSubType: "hotel-bar",
      displayCount: 0,
      coldBoxCount: 6,
      hasWindows: true,
      shelfFacings: 0,
      backbarPresence: true,
      menuPlacement: true,
      footTrafficEstimate: "high",
      notes: "High volume rooftop. Perfect for spritz campaigns.",
      lastSurveyDate: "2026-03-05",
    },
    eventsHosted: 6,
    lastEventDate: "2026-03-15",
    createdAt: "2024-11-05T08:00:00Z",
    updatedAt: "2026-03-05T10:00:00Z",
  },
  {
    id: "acc-6",
    name: "Joe's Tavern",
    type: "on-premise",
    status: "inactive",
    address: "199 Dive St",
    city: "Jersey City",
    state: "NJ",
    zipCode: "07302",
    contactName: "Joe Miller",
    contactPhone: "(201) 555-0199",
    profile: {
      venueSubType: "dive-bar",
      displayCount: 0,
      coldBoxCount: 2,
      hasWindows: false,
      shelfFacings: 0,
      backbarPresence: true,
      menuPlacement: false,
      footTrafficEstimate: "low",
      notes: "Currently under renovation. Paused all activations.",
    },
    eventsHosted: 2,
    lastEventDate: "2025-08-10",
    createdAt: "2024-02-12T08:00:00Z",
    updatedAt: "2025-10-01T10:00:00Z",
  },
];

export function generateAccountId(): string {
  return `acc-${Math.floor(Math.random() * 10000)}`;
}
