import type { Educator } from "../../shared/data/shared-types";

/* ------------------------------------------------------------------ */
/* Mock educator data — follows account-data.ts pattern                */
/* ------------------------------------------------------------------ */

export const MOCK_EDUCATORS: Educator[] = [
  {
    id: "EDU-001",
    name: "Maria Santos",
    city: "New York",
    state: "NY",
    status: "active",
    qualityScore: 94,
    trend: "up",
    eventsCompleted: 47,
    specialties: ["Spirits", "Wine", "Cocktail Mixing"],
    lastEventDate: "2026-03-14",
  },
  {
    id: "EDU-002",
    name: "James Mitchell",
    city: "Brooklyn",
    state: "NY",
    status: "active",
    qualityScore: 88,
    trend: "stable",
    eventsCompleted: 32,
    specialties: ["Beer", "Craft Spirits"],
    lastEventDate: "2026-03-12",
  },
  {
    id: "EDU-003",
    name: "Ashley Chen",
    city: "Jersey City",
    state: "NJ",
    status: "active",
    qualityScore: 91,
    trend: "up",
    eventsCompleted: 38,
    specialties: ["Wine", "Spirits", "Brand Education"],
    lastEventDate: "2026-03-15",
  },
  {
    id: "EDU-004",
    name: "David Kowalski",
    city: "Hoboken",
    state: "NJ",
    status: "pending",
    qualityScore: 0,
    trend: "stable",
    eventsCompleted: 0,
    specialties: ["Beer", "Wine"],
    lastEventDate: null,
  },
  {
    id: "EDU-005",
    name: "Sophia Rivera",
    city: "Miami",
    state: "FL",
    status: "active",
    qualityScore: 96,
    trend: "up",
    eventsCompleted: 61,
    specialties: ["Tequila", "Spirits", "Cocktail Mixing"],
    lastEventDate: "2026-03-16",
  },
  {
    id: "EDU-006",
    name: "Marcus Taylor",
    city: "Fort Lauderdale",
    state: "FL",
    status: "active",
    qualityScore: 82,
    trend: "down",
    eventsCompleted: 19,
    specialties: ["Beer", "Spirits"],
    lastEventDate: "2026-02-28",
  },
  {
    id: "EDU-007",
    name: "Lauren Nguyen",
    city: "Stamford",
    state: "CT",
    status: "active",
    qualityScore: 90,
    trend: "stable",
    eventsCompleted: 28,
    specialties: ["Wine", "Brand Education"],
    lastEventDate: "2026-03-10",
  },
  {
    id: "EDU-008",
    name: "Chris Bennett",
    city: "Bridgeport",
    state: "CT",
    status: "inactive",
    qualityScore: 71,
    trend: "down",
    eventsCompleted: 12,
    specialties: ["Beer"],
    lastEventDate: "2025-11-22",
  },
  {
    id: "EDU-009",
    name: "Jasmine Williams",
    city: "Manhattan",
    state: "NY",
    status: "active",
    qualityScore: 87,
    trend: "up",
    eventsCompleted: 35,
    specialties: ["Spirits", "Cocktail Mixing", "Brand Education"],
    lastEventDate: "2026-03-13",
  },
  {
    id: "EDU-010",
    name: "Kevin O'Brien",
    city: "Newark",
    state: "NJ",
    status: "active",
    qualityScore: 79,
    trend: "stable",
    eventsCompleted: 22,
    specialties: ["Beer", "Craft Spirits", "Wine"],
    lastEventDate: "2026-03-08",
  },
  {
    id: "EDU-011",
    name: "Natalia Perez",
    city: "Orlando",
    state: "FL",
    status: "pending",
    qualityScore: 0,
    trend: "stable",
    eventsCompleted: 0,
    specialties: ["Tequila", "Cocktail Mixing"],
    lastEventDate: null,
  },
  {
    id: "EDU-012",
    name: "Tyler Robinson",
    city: "Queens",
    state: "NY",
    status: "active",
    qualityScore: 85,
    trend: "up",
    eventsCompleted: 26,
    specialties: ["Spirits", "Wine"],
    lastEventDate: "2026-03-11",
  },
];
